### ISSUE TITLE
Can't use terraform destroy correctly

### ISSUE THREAD

**Issue by iliapisaniy** [timeweb-cloud/terraform-provider-timeweb-cloud#21] opened 2024-06-26 02:18 UTC
### What i did
I created some servers using twc_server resource and assigned ip to some using twc_server_ip resource. After i tried to destroy these resources and get the error: i can't delete vds ip because it is in use

### What i got
```
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

twc_server_ip.n2: Destroying... [id=<id was here>-<ip was here>]
twc_server_ip.n1: Destroying... [id=<id was here>-<ip was here>]
╷
│ Error: can't delete VDS IP: can't delete VDS IP: received api error; status_code: 400, message: Can`t delete main ip, error_code: delete_main_ip_error, response_id: cf433694-1703-4685-b360-70b0c7854102
│ 
│ 
╵
╷
│ Error: can't delete VDS IP: can't delete VDS IP: received api error; status_code: 400, message: Can`t delete main ip, error_code: delete_main_ip_error, response_id: 6995e90f-628f-4563-9be8-b29645a8cf17
│ 
│ 
╵
```

### Environment
```
Terraform v1.8.5
on darwin_arm64
+ provider tf.timeweb.cloud/timeweb-cloud/timeweb-cloud v1.3.6
```

**Comment by DCFrog** [comment] 2024-12-14 20:05
Something similar for me when deleting server with attached firewall and IP address.
I'm getting 500 server error on firewall deletion:
![image](https://github.com/user-attachments/assets/2d3ccbbf-a842-4682-a5ca-81dd69dd6edd)

After waiting some seconds and retrying - everything gets destroyed with any issues.
Please fix as this is really annoying..

**Comment by mfbeach** [comment] 2024-12-26 09:54
> Something similar for me when deleting server with attached firewall and IP address. I'm getting 500 server error on firewall deletion: ![image](https://private-user-images.githubusercontent.com/150377458/395815312-2d3ccbbf-a842-4682-a5ca-81dd69dd6edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDcwODYsIm5iZiI6MTczNTIwNjc4NiwicGF0aCI6Ii8xNTAzNzc0NTgvMzk1ODE1MzEyLTJkM2NjYmJmLWE4NDItNDY4Mi1hNWNhLTgxZGQ2OWRkNmVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwOTUzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTk1MDY0NGRkYzE0ODE1MjMwZDZlZTQzZTAwMDM4ZjIxNmIyNTk1M2QzZDk5MTYwODdjMWNiOGE0OTM5ODY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xlCr-KlkLVNDUIJldWyIyQUdKHr_jU6ewyMkPNy1en0)
> 
> After waiting some seconds and retrying - everything gets destroyed with any issues. Please fix as this is really annoying..

Firewall rules deletion should be fixed in the latest release. Could you check it?

**Comment by mfbeach** [comment] 2024-12-26 09:58
> ### What i did
> I created some servers using twc_server resource and assigned ip to some using twc_server_ip resource. After i tried to destroy these resources and get the error: i can't delete vds ip because it is in use
> 
> ### What i got
> ```
> Do you really want to destroy all resources?
>   Terraform will destroy all your managed infrastructure, as shown above.
>   There is no undo. Only 'yes' will be accepted to confirm.
> 
>   Enter a value: yes
> 
> twc_server_ip.n2: Destroying... [id=<id was here>-<ip was here>]
> twc_server_ip.n1: Destroying... [id=<id was here>-<ip was here>]
> ╷
> │ Error: can't delete VDS IP: can't delete VDS IP: received api error; status_code: 400, message: Can`t delete main ip, error_code: delete_main_ip_error, response_id: cf433694-1703-4685-b360-70b0c7854102
> │ 
> │ 
> ╵
> ╷
> │ Error: can't delete VDS IP: can't delete VDS IP: received api error; status_code: 400, message: Can`t delete main ip, error_code: delete_main_ip_error, response_id: 6995e90f-628f-4563-9be8-b29645a8cf17
> │ 
> │ 
> ╵
> ```
> 
> ### Environment
> ```
> Terraform v1.8.5
> on darwin_arm64
> + provider tf.timeweb.cloud/timeweb-cloud/timeweb-cloud v1.3.6
> ```

It will really help if you provide manifest example.

**Comment by iliapisaniy** [comment] 2024-12-26 19:38
@mfbeach i found this configuration on my laptop. But i don't remember if i changed this config or not since created this issue because it was for a long time ago. Currently this config runs and destroys without issues

```hcl
terraform {
  required_providers {
    twc = {
      source = "tf.timeweb.cloud/timeweb-cloud/timeweb-cloud"
    }
  }
}

data "twc_s3_preset" "keys" {
  location = "ru-1"
  disk = 10*1024
  price_filter {
    from = 1
    to = 100
  }
}

data "twc_os" "main_ubuntu" {
  name    = "ubuntu"
  version = "22.04"
}


resource "twc_vpc" "vpc" {
  count     = 2
  name      = "vpc${count.index + 1}"
  subnet_v4 = "192.168.${10 + count.index}.0/24"
  location  = "ru-1"
}

resource "twc_server" "n1" {
  count = 2

  name         = "server ${count.index + 1} of vpc 1"
  os_id        = data.twc_os.main_ubuntu.id
  preset_id    = 2447
  ssh_keys_ids = <redacted>
  local_network {
    id = twc_vpc.vpc[0].id
    ip = "192.168.10.${10 + count.index}"
  }
}

resource "twc_server" "n2" {
  count = 1

  name         = "server ${count.index + 1} of vpc 2"
  os_id        = data.twc_os.main_ubuntu.id
  preset_id    = twc_server.n1[0].preset_id
  ssh_keys_ids = <redacted>
  local_network {
    id = twc_vpc.vpc[1].id
    ip = "192.168.11.${10 + count.index}"
  }
}

resource "twc_server_ip" "n1" {
  source_server_id = twc_server.n1[0].id
  type             = "ipv4"
}

resource "twc_server_ip" "n2" {
  source_server_id = twc_server.n2[0].id
  type             = "ipv4"
}
```

**Comment by mfbeach** [comment] 2024-12-27 09:22
@iliapisaniy Thank you for the manifest. Just tested it and some other manifests, everything seems to be all right. As the issue is not reproducible anymore I will close it.

**Closed by mfbeach** 2024-12-27 09:22 UTC
